#!/bin/sh
#                               _
#  ___ _ __   ___ _ __ ___   __| |
# / __| '_ \ / __| '_ ` _ \ / _` |
# \__ | |_) | (__| | | | | | (_| |
# |___| .__/ \___|_| |_| |_|\__,_|
#     |_|
# Created by: spcmd
# http://spcmd.github.io
# https://github.com/spcmd

# List ebooks from Calibre Library directory and open them with ebook-viewer or zathura (PDF files)
# Requires: calibre, zathura

# Calibre Library directory
dir_calibre="$HOME/Calibre Library"

# Set dmenu style
[ -f "$HOME/.dmenurc" ] && . "$HOME/.dmenurc" || DMENU='dmenu -i -l 10'

# List ebooks sorted (sed out the path; show only the directories and the filenames)
list_ebooks=$(find "$dir_calibre" -iregex '.*\.\(epub\|pdf\)$'| sed "s#$dir_calibre/##" | sort)

# Select ebook from dmenu
get_ebook=$(echo "$list_ebooks" | $DMENU)

if [ ! -z "$get_ebook" ]; then
    notify-send "Opening ebook:" "$(echo $get_ebook | awk -F'/' '{print $NF}')"
    if [ "${get_ebook##*.}" = "pdf" ]; then
        zathura "$dir_calibre/$get_ebook"
    else
        ebook-viewer "$dir_calibre/$get_ebook"
    fi
else
    exit
fi
