#!/bin/bash

# Copy updated site content generated by jekyll to the site directory under git

JEKYLL_SITE_DIR=~/.xampp/spcmd/_site
GIT_SITE_DIR=~/git/spcmd.github.io

if [[ -d "$JEKYLL_SITE_DIR" ]] && [[ -d "$GIT_SITE_DIR" ]]; then
	cp -R $JEKYLL_SITE_DIR/* $GIT_SITE_DIR
	echo "Finished copying site to $GIT_SITE_DIR"
elif [[ ! -d "$JEKYLL_SITE_DIR" ]] && [[ ! -d "$GIT_SITE_DIR" ]]; then
	echo "Error! Can't find directories:"
	echo " $JEKYLL_SITE_DIR"
	echo " $GIT_SITE_DIR"
elif [[ ! -d "$JEKYLL_SITE_DIR" ]]; then
	echo "Error! Can't find directory: $JEKYLL_SITE_DIR"
elif [[ ! -d "$GIT_SITE_DIR" ]]; then	
	echo "Error! Can't find directory: $GIT_SITE_DIR"
else 
	echo "Error, something went wrong, check the script!"
fi