#!/bin/bash

#Source: https://gopherproxy.meulie.net/uninformativ.de/0/twitpher/2012-05/2012-05-16.txt

#luakit  has  its own NoScript implementation (of course). Its downside
#is that the database is stored as an sqlite database. This is not much
#of  a  problem  unless  you want to sync your dotfiles. Every time the
#file "~/.local/share/luakit/noscript.db" is written, it's being marked
#as "changed". Annoying.

#I surely could rewrite luakit's "noscript.lua". But I don't want to do
#that. Instead I now use this wrapper script.

#This allows me to store my NoScript rules in "noscript.sql"  --  plain
#text.  When  luakit  is  being  started, a new sqlite db gets created.
#When luakit is quit, my "noscript.sql" gets updated.

#That's far more convenient than having to deal with binary files in my
#dotfiles-repository. 

sql=~/.local/share/luakit/noscript.sql
db=~/.local/share/luakit/noscript.db

if ! pgrep '^luakit$'
then
         : > $db
         sqlite3 $db < $sql
         luakit "$@"
         sqlite3 $db '.dump by_domain' > $sql
else
         luakit "$@"
fi
