#!/bin/sh
#                               _
#  ___ _ __   ___ _ __ ___   __| |
# / __| '_ \ / __| '_ ` _ \ / _` |
# \__ | |_) | (__| | | | | | (_| |
# |___| .__/ \___|_| |_| |_|\__,_|
#     |_|
# Created by: spcmd
# http://spcmd.github.io
# https://github.com/spcmd

# simple command line note

FILE_NOTES=$HOME/Documents/Notes

colorize_output(){ sed -r -e "s/\[.+\]/\o033[0;32m&\o033[0m/" -e "s/@.+/\o033[0;30;46;3m & \o033[0m/"; }

usage() {
cat <<EOF
Notes file's location: $FILE_NOTES
Usage: $(basename $0) [option] <note|keyword>

Options:
<note>                                      Add a note (you can add a note without using the -a or the --add option)
-a, --add <note>                            Add a note
-b, --backup                                Create a backup copy in the same directory
-e, --edit                                  Edit Notes file directory (with $EDITOR)
-r, --remove <keyword>                      Remove note(s) by keyword (a keyword can be any word, tag, date or time)
-R, --remove-all                            Remove ALL notes (emergency backup will be created in /tmp)
-l, --list                                  List notes (show newer first)
-L, --list-oldest-first                     List notes (show oldest first)
-s, --search <keyword>                      Search in the notes (case-insensitive)
-S, --search-case-sensitive <keyword>       Search in the notes (case-sensitive)
-h, --help                                  This help

Important: Use quoting for the notes! Use @ for tagging, e.g.:

note "This is my first note @mytag"         This will add a note with the tag @mytag
note -r "13:22"                             This will remove note(s) with the 13:22 timestamp
note -r "@mytag"                            This will remove note(s) with the tag @mytag

EOF
}

case "$1" in

    -b|--backup) cp $FILE_NOTES $FILE_NOTES.bak ;;
    -r|--remove) sed -i "/$2/d" $FILE_NOTES ;;
    -R|--remove-all)
                    echo "Remove ALL notes? Are you sure [yY/nN]"
                    read answer
                    if [ "$answer" = "y" -o "$answer" = "Y" ]; then
                        cp $FILE_NOTES /tmp
                        rm $FILE_NOTES
                        echo "$FILE_NOTES has been deleted. Now you can find a copy in /tmp (for emergency) until the next reboot. Delete manually if you wish."
                    else
                        echo "Cancelled."
                    fi
                    ;;

    -l|--list) tac $FILE_NOTES | colorize_output ;;
    -L|--list-oldest-first) cat $FILE_NOTES | colorize_output ;;
    -s|--search) grep -i "$2" $FILE_NOTES | colorize_output ;;
    -S|--search-case-sensitive) grep "$2" $FILE_NOTES | colorize_output;;
    -e|--edit) $EDITOR $FILE_NOTES ;;
    -h|--help) usage;;
    -a|--add) echo "$(date +"[%Y-%b-%d %H:%M]") $2" >> $FILE_NOTES ;;
    -*) echo "Invalid option. Use '$0 -h' for help." ;;
    *)
        if [ -z "$1" ]; then
            tac $FILE_NOTES | colorize_output
        else
            echo "$(date +"[%Y-%b-%d %H:%M]") $@" >> $FILE_NOTES
        fi
        ;;
esac
