#!/bin/bash
#                               _
#  ___ _ __   ___ _ __ ___   __| |
# / __| '_ \ / __| '_ ` _ \ / _` |
# \__ | |_) | (__| | | | | | (_| |
# |___| .__/ \___|_| |_| |_|\__,_|
#     |_|
# Created by: spcmd
# https://github.com/spcmd

# A wrapper script from pyrocore/rtcontrol using with rtorrent-ps


# got this from: $d.name=
# change bracketed strings and comma to '*' character
name=$(echo "$2" | sed -re 's/\[.+\]/*/g;s/,/*/g')

# got this from: $argument.0=
tag=$3

# do the stuff
case $1 in
    --add-tag)
            rtcontrol "${name}*" --tag="${tag}"
            ;;
    --remove-tag)
            rtcontrol "${name}*" --tag="-${tag}"
            ;;
    --remove-tag-all)
            rtcontrol tagged="${tag}" --tag="-${tag}"
            ;;
    *)
        exit 0;
esac
