#!/bin/bash
#                                      _
#         ___ _ __   ___ _ __ ___   __| |
#        / __| '_ \ / __| '_ ` _ \ / _` |
#        \__ | |_) | (__| | | | | | (_| |
#        |___| .__/ \___|_| |_| |_|\__,_|
#             |_|
#
#              spotify-album-export
#               Created by: spcmd
#           http://spcmd.github.io
#           https://github.com/spcmd
#           https://gist.github.com/spcmd
#
# This script allows you to export your album list from spotify
# to json format and then extract infromation from it, then make
# a simple album list. All with one simple command.

# The final format of the album list file will be:
#   artist|album|spotify_uri
#   artist|album|spotify_uri
#   ...and so on

# Then you can process this file as you wish, for example
# you can pipe it to dmenu with a script (like spotymenu).

# Acknowledgement
# This script uses JSON.awk to format the exported json file.
# JSON.awk was written by step: https://github.com/step-/JSON.awk

# Related Spotify Documentation:
# https://developer.spotify.com/web-api/get-users-saved-albums/

# Get token here:
# https://developer.spotify.com/web-api/console/get-current-user-saved-albums/
# Never include your token in this script!
# You pass your token in the command line for this script.

# --------------------
# --- Configurable ---
# --------------------

# The maximum number of objects to return. Default: 20. Minimum: 1. Maximum: 50.
limit="50" # use the max

# Set the file paths
file_extracted_json=/tmp/spotify_exported_album_list.json
file_albumlist=~/spoty_albums
file_json_awk=~/Scripts/JSON.awk

# -----------------
# --- Functions ---
# -----------------

error_json_awk() {
    echo "Error: cannot find $file_json_awk"
    echo "You need to set the correct path for the file_json_awk variable in the script."
}

get_album_list() {
    if [[ -z $token ]]; then
        echo -e "Error: you need to specify a token!\n"
        usage
        exit 1
    fi

    if [[ -f "$file_json_awk" ]];then
        curl --silent -X GET "https://api.spotify.com/v1/me/albums?limit=$limit" -H "Accept: application/json" -H "Authorization: Bearer $token" > $file_extracted_json && echo -e "$file_extracted_json" | awk -f "$file_json_awk" | awk -F']' '/^\["items",[0-9]{1,2},"album","artists",0,"name"\]/{gsub(/^[ \t]+/, "", $2);gsub(/"/,"", $2);print $2"|"} /^\["items",[0-9]{1,2},"album","name"\]/{gsub(/^[ \t]+/, "", $2);gsub(/"/,"", $2);print $2"|"} /^\["items",[0-9]{1,2},"album","id"\]/{gsub(/^[ \t]+/, "", $2);gsub(/"/,"", $2);print $2}' | sed -n 'p;n;h;n;G;p' | sed '$!N;$!N;s/\n//g' >> $file_albumlist && echo "Done. You can find the album list here: $file_albumlist"
    else
        error_json_awk
        exit 1
    fi
}

get_album_list_with_offset() {
    if [[ -z $offset ]] || [[ -z $token ]]; then
        echo -e "Error: you need to specify an offset number and then a token!\n"
        usage
        exit 1
    fi

    if [[ -f "$file_json_awk" ]];then
        curl --silent -X GET "https://api.spotify.com/v1/me/albums?offset=$offset&limit=$limit" -H "Accept: application/json" -H "Authorization: Bearer $token" > $file_extracted_json && echo -e "$file_extracted_json" | awk -f "$file_json_awk" | awk -F']' '/^\["items",[0-9]{1,2},"album","artists",0,"name"\]/{gsub(/^[ \t]+/, "", $2);gsub(/"/,"", $2);print $2"|"} /^\["items",[0-9]{1,2},"album","name"\]/{gsub(/^[ \t]+/, "", $2);gsub(/"/,"", $2);print $2"|"} /^\["items",[0-9]{1,2},"album","id"\]/{gsub(/^[ \t]+/, "", $2);gsub(/"/,"", $2);print $2}' | sed -n 'p;n;h;n;G;p' | sed '$!N;$!N;s/\n//g' >> $file_albumlist && echo "Done. You can find the album list here: $file_albumlist"

    else
        error_json_awk
        exit 1
    fi
}

add_by_uri(){
    if [[ -z $uri ]]; then
        echo -e "Error: you need to specify a spotify_uri!\n"
        usage
        exit 1
    fi

    album_id=$(echo "$uri" | awk -F ':' '{print $3}')
    curl --silent -X GET "https://api.spotify.com/v1/albums/$album_id" > $file_extracted_json && echo -e "$file_extracted_json" | awk -f "$file_json_awk" | awk -F']' -v album_id="$album_id" '/^\["artists",[0-9]{1,2},"name"\]/{gsub(/^[ \t]+/, "", $2);gsub(/"/,"", $2);print $2"|"} /^\["name"\]/{gsub(/^[ \t]+/, "", $2);gsub(/"/,"", $2);print $2"|"album_id}' | sed '$!N;$!N;s/\n//g' >> $file_albumlist && echo "Done. You can find the album list here: $file_albumlist"
}

usage() {
    echo -e "Usage: $(basename $0) [option] [token]\n"
    echo "You can get your personal token here (after logged in to spotify):"
    echo -e "https://developer.spotify.com/web-api/console/get-current-user-saved-albums/\n"
    echo "Options:"
    echo "              -o <offset> <token>     Offset number: begin the extraction from here. You have to specify the token after it."
    echo "              -a <uri>                Add album to the album list by a spotify_uri (e.g.: spotify:album:41bTjcSaiEe4G40RVVHbux)"
    echo "                                      In this script the default limit is 50 so you might want to use '-o 50' to get the next 50 on the second run,"
    echo "                                      then '-o 100' on the third run and so on)."
    echo "              -h                      This help page."
}

# ----------------------
# --- Case Statement ---
# ----------------------

case "$1" in
    -o) offset="$2" token="$3" get_album_list_with_offset;;
    -a) uri="$2" add_by_uri;;
    -h) usage;;
    *) token="$1" get_album_list;;
esac
