#!/bin/bash
#                                      _
#         ___ _ __   ___ _ __ ___   __| |
#        / __| '_ \ / __| '_ ` _ \ / _` |
#        \__ | |_) | (__| | | | | | (_| |
#        |___| .__/ \___|_| |_| |_|\__,_|
#             |_|
#
#                   spotymenu
#               Created by: spcmd
#           http://spcmd.github.io
#           https://github.com/spcmd
#           https://gist.github.com/spcmd
#
#

#==================================
# Configurable Options
#==================================

# Dir where spotymenu stores its config and lists
#dir_spotymenu=$HOME/spotymenu

# File that contains the album list
file_albumlist=$HOME/.spoty_albums

# File that contains the list of playlists
file_playlists=$HOME/.spoty_playlists

# Default file where the favorites saved to
file_favorite_tracks=$HOME/favorite_tracks

# Artist and Album separator in the displayed -dmenu- list
separator=" - "

# Colors
font="monospace-10"
list_size="20"
normal_bg="#181818"
normal_fg="#ccc"
selected_bg="#1DB954"
selected_fg="#181818"
selected_delete_bg="#c30000"
selected_delete_fg="#ffffff"

# Show currently playing track info at the top of the list
show_playing_track="yes"

# Playing track prefix string and separator line
playing_track_prefix=">>> Playing: "
playing_track_separator="\n---------------------------------------------------------------------------------------------"

# Autoplay selected album (local album list), yes or no/empty
autoplay_album="yes"

# Autoplay search result, yes or no/empty
autoplay_search_result="yes"

# Search history
use_search_history="yes"
file_search_history=$HOME/.spoty_search_history

# For Awesome WM: switch to spotify's tag after selecting or searching
awm_switch="yes" # yes or no/empty
awm_screen="1"
awm_tag="4"

# Confirm quit OR quit without warning?
confirm_quit="yes"

#==================================
# Functions and variables
#==================================

# dbus calls
dbus_stop="dbus-send  --print-reply --session --type=method_call --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Stop"
dbus_openuri="dbus-send --print-reply=literal --session --type=method_call --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.OpenUri"
dbus_get_meta="dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata"

# currently playing song
playing_artist=$($dbus_get_meta | awk 'gsub("\042","")sub("string","")gsub(/^[ \t]+/,"")c&&!--c;/artist/{c=2}')
playing_albumartist=$($dbus_get_meta | awk 'gsub("\042","")sub("string","")gsub(/^[ \t]+/,"")c&&!--c;/albumArtist/{c=2}')
playing_title=$($dbus_get_meta | awk 'f{$1=$2=""; gsub("\042",""); gsub(/^[ \t]+/,""); print $0;f=0} /"xesam:title"/{f=1}')
playing_album=$($dbus_get_meta |awk 'f{$1=$2=""; gsub("\042",""); gsub(/^[ \t]+/,""); print $0;f=0} /"xesam:album"/{f=1}')
playing_tracknr=$($dbus_get_meta | awk 'f{$1=$2=""; gsub("\042",""); gsub(/^[ \t]+/,""); print $0;f=0} /"xesam:trackNumber"/{f=1}')
playing_trackid=$($dbus_get_meta | awk 'f{$1=$2=""; gsub("\042",""); gsub(/^[ \t]+/,""); print $0;f=0} /"mpris:trackid"/{f=1}')
playing_arturl=$($dbus_get_meta | awk 'f{$1=$2=""; gsub("\042",""); gsub(/^[ \t]+/,""); print $0;f=0} /"mpris:artUrl"/{f=1}')

playing_length=$($dbus_get_meta | awk 'f{$1=$2=""; gsub("\042",""); gsub(/^[ \t]+/,""); print $0;f=0} /"mpris:length"/{f=1}')
playing_seconds=$(($playing_length/1000000))
playing_min_sec=$(printf ""%d:%02d"\n" $(($playing_seconds%3600/60)) $(($playing_seconds%60)))


awm_switch_to_tag() {
    echo "local awful = require('awful') ; return awful.tag.viewonly(tags[$awm_screen][$awm_tag])" | awesome-client
}

search_album() {
    type="album"
    query=$(echo "$input" | sed -e 's|/album||' -e 's|/b||' -e 's/ /+/g')
    api_url="https://api.spotify.com/v1/search?q=$query&type=$type"

    # record search query to history?
    if [[ $use_search_history = "yes" ]]; then
        echo "$input" >> $file_search_history
    fi

    # run search
    spotify_uri="$(curl -s "$api_url" | grep --color=never -E -o "spotify:$type:[a-zA-Z0-9]+" -m 1)"
    $dbus_openuri "string:$spotify_uri"
    # awesome wm - switch to spotify's tag
    if [[ $awm_switch = "yes" ]]; then
        awm_switch_to_tag
    fi
}

search_artist() {
    type="artist"
    query=$(echo "$input" | sed -e 's|/artist||' -e 's|/a||' -e 's/ /+/g')
    api_url="https://api.spotify.com/v1/search?q=$query&type=$type"

    # record search query to history?
    if [[ $use_search_history = "yes" ]]; then
        echo "$input" >> $file_search_history
    fi

    # run search
    spotify_uri="$(curl -s "$api_url" | grep --color=never -E -o "spotify:$type:[a-zA-Z0-9]+" -m 1)"
    $dbus_openuri "string:$spotify_uri"
    # awesome wm - switch to spotify's tag
    if [[ $awm_switch = "yes" ]]; then
        awm_switch_to_tag
    fi
}
search_default() {
    type="track"
    query=$(echo "$input" | sed -e 's|/||' -e 's/ /+/g')
    api_url="https://api.spotify.com/v1/search?q=$query&type=$type"
    if [[ $autoplay_search_result = "yes" ]]; then
        dbus_call() { $dbus_stop && $dbus_openuri "string:$spotify_uri" > /dev/null; }
    else
        dbus_call() { $dbus_openuri "string:$spotify_uri"; }
    fi

    # record search query to history?
    if [[ $use_search_history = "yes" ]]; then
        echo "$input" >> $file_search_history
    fi

    # run search
    spotify_uri="$(curl -s "$api_url" | grep --color=never -E -o "spotify:$type:[a-zA-Z0-9]+" -m 1)"
    dbus_call

    # awesome wm - switch to spotify's tag
    if [[ $awm_switch = "yes" ]]; then
        awm_switch_to_tag
    fi
}

#==================================
# Do the stuff
#==================================

# 0. dmenu styling
DMENU="dmenu -i -l $list_size -fn $font -nb $normal_bg -nf $normal_fg -sb $selected_bg -sf $selected_fg"
DMENU_DELETE="dmenu -i -l $list_size -fn $font -nb $normal_bg -nf $normal_fg -sb $selected_delete_bg -sf $selected_delete_fg"

# 1. Pipe album list to dmenu

if [[ ! -f $file_albumlist ]]; then
    echo "Error: can't find $file_albumlist" | $DMENU
else
    if [[ $show_playing_track = "yes" ]]; then
        input=$(awk -F '|' \
            -v sep="$separator" \
            -v artist="$playing_artist" \
            -v title="$playing_title" \
            -v album="$playing_album" \
            -v psep="$playing_track_separator" \
            -v pfx="$playing_track_prefix" \
            'BEGIN {print pfx artist sep title" ("album")"psep}{print $1 sep $2}' $file_albumlist \
            | $DMENU)
    else
        input=$(awk -F '|' \
            -v sep="$separator" \
            '{print $1 sep $2}' $file_albumlist \
            | $DMENU)
    fi
fi

# --- Search ---
# search for: album
if [[ $input = /album* ]] || [[ $input = /b* ]]; then
        search_album
    # search for: artist
elif [[ $input = /artist* ]] || [[ $input = /a* ]]; then
        search_artist
    # search for artist and/or track
elif [[ $input = /* ]]; then
        search_default

    # -- DEBUG ---
    #echo -e "This was a search for: \033[0;33m$query\033[0m"
    #echo -e "type: \033[0;33m$type\033[0m"
    #echo -e "spotify_uri: \033[0;33m$spotify_uri\033[0m"

# --- Show the search history ---
elif [[ $input = ? ]]; then

    if [[ $use_search_history = "yes" ]]; then

        if [[ ! -f $file_search_history ]]; then
            echo "Error: can't find $file_search_history" | $DMENU
        else
            search_string=$(tac $file_search_history | uniq | $DMENU)
            if [[ $search_string = /b* ]] || [[ $search_string = /album* ]]; then
                input="$search_string" && search_album
            elif [[ $search_string = /a* ]] || [[ $search_string = /artist* ]]; then
                input="$search_string" && search_artist
            elif [[ $search_string = /* ]]; then
                input="$search_string" && search_default
            else
                exit
            fi
        fi

    else
        exit
    fi

# --- Switch to the playlists ---
elif [[ $input = :playlist ]] || [[ $input = :p ]]; then

    if [[ ! -f $file_playlists ]]; then
        echo "Error: can't find $file_playlists" | $DMENU
    else
        playlist=$(awk -F '|' '{print $1}' $file_playlists | $DMENU)
        playlist_uri=$(awk -F '|' 'index($0, "'"$playlist"'"){print $NF}' $file_playlists | head -n 1)

        if [[ -z $playlist ]]; then
            exit
        else
            $dbus_openuri "string:$playlist_uri"
            if [[ $awm_switch = "yes" ]]; then
                awm_switch_to_tag
            fi
        fi
    fi

# --- Quit/Close Spotify ---
elif [[ $input = :quit ]] || [[ $input = :q ]]; then
    if [[ $confirm_quit = "yes" ]]; then
        quit_answer=$(echo -e "Are you sure you want to close Spotify?\nyes\nno" | $DMENU)
        [[ $quit_answer = "yes" ]] && pkill -SIGTERM spotify || exit
    else
        pkill -SIGTERM spotify
    fi

# --- Detailed Info about the played album/song ---
elif [[ $input = :info ]] || [[ $input = :i ]]; then
    infolist=$(echo -e "\
     Information:  (press Enter to copy the entry to the clipboard)\n\
     ==============================================================\n\
     Artist: $playing_artist\n\
      Title: $playing_title\n\
      Album: $playing_album\n\
      Track: $playing_tracknr\n\
     Length: $playing_min_sec\n\
         ID: $playing_trackid\n\
      Cover: $playing_arturl\n\
     ==============================================================\
     " | $DMENU)

    echo "$infolist" | awk '{$1="";gsub(/^[ \t]+/, "");print $0}' | xsel -b

# --- Add current album to the album list ---
elif [[ $input = :add ]] || [[ $input = :a ]]; then
    query=$(echo "$playing_album" | sed -e 's/ /+/g' -re 's/:|\(|\)|\.//g')
    playing_albumid=$(curl -s "https://api.spotify.com/v1/search?q=$query&type=album" | awk -F':' '/spotify:album:.+/{gsub(/^[ \t]+/, "");gsub("\042","");print $NF;exit}')
    if [[ ! -z $playing_albumid ]]; then
        add_answer=$(echo -e "Add '$playing_album' to the albumlist?\nyes\nno" | $DMENU)
        [[ $add_answer = "yes" ]] && echo "$playing_albumartist|$playing_album|$playing_albumid" >> $file_albumlist\
           && echo -e "Done:\n'$playing_album' added to the album list\n" | $DMENU \
           || exit
    else
        exit
    fi

# --- Album TRACKLIST ---
elif [[ $input = :t* ]] || [[ $input = $playing_track_prefix* ]]; then
    query=$(echo "$playing_album" | sed -e 's/ /+/g' -re 's/:|\(|\)|\.//g')
    playing_albumid=$(curl -s "https://api.spotify.com/v1/search?q=$query&type=album" | awk -F':' '/uri/{gsub(/^[ \t]+/, "");gsub("\042","");print $NF;exit}')
    if [[ ! -z $playing_albumid ]]; then
        tracklist=$(curl --silent -X GET "https://api.spotify.com/v1/albums/$playing_albumid/tracks?limit=50" | jq -r '.items | map([.track_number, .artists[].name, .name, .id | tostring] | join("|")) | join("\n")' | awk -v len=30 -v pfx="$playing_track_prefix" 'BEGIN{printf "%-6s%-35s%-35s%-30s%-80s%-80s\n","Nr.","Artist","Title","ID","\n----------------------------------------------------------------------------------------\n",pfx"'"$playing_tracknr $playing_title"'"}{if(length($1)>len) $1=substr($1,1,30)"..."; if(length($2)>len) $2=substr($2,1,30)"..."; if(length($3)>len) $3=substr($3,1,30)"..."; printf "%-6s%-35s%-35s%-30s\n",$1,$2,$(NF-1),$NF}' FS=\| | $DMENU)
        track_id=$(echo "$tracklist" | awk '{print $NF}')
        if [[ ! -z $track_id ]]; then
            $dbus_stop && $dbus_openuri "string:spotify:track:$track_id"
        else
            exit
        fi
    else
        exit
    fi

# --- Delete album from the album list ---
elif [[ $input = :del* ]] || [[ $input = :d ]]; then

    if [[ ! -f $file_albumlist ]]; then
        echo "Error: can't find $file_albumlist" | $DMENU
    else
        input=$(awk -F '|' -v sep="$separator" '{print $1 sep $2}' $file_albumlist | $DMENU_DELETE)
        get_album=$(echo "$input" | awk -v sep="$separator" '{sub(sep,"|");print}')
        album_id=$(awk -F '|' 'index($0, "'"$get_album"'"){print $NF}' $file_albumlist | head -n 1)

        if [[ ! -z $input ]]; then
            delete_answer=$(echo -e "Delete '$input' from the albumlist?\nyes\nno" | $DMENU_DELETE)
            [[ $delete_answer = "yes" ]] && sed -i "/$album_id/d" $file_albumlist\
            && echo -e "Done:\n'$input' deleted from the album list\n" | $DMENU_DELETE \
            || exit
        else
            exit
        fi
    fi

# --- Favorite tracks: ADD ---
elif [[ $input = :fadd ]] || [[ $input = :fa ]]; then

    echo "$playing_artist|$playing_title|$playing_album|$playing_min_sec|$playing_trackid" >> $file_favorite_tracks &&\
    echo -e "Done:\n'$playing_artist - $playing_title' added to the favorites.\n" | $DMENU

# --- Favorite tracks: DELETE ---
elif [[ $input = :fd* ]]; then

    get_track=$(awk -v len=30 'BEGIN{printf "%-30s%-35s%-35s%-6s%-38s%-100s\n","Artist","Title","Album","Time","URI","\n----------------------------------------------------------------------------------------------------------------------------------------------"}{if(length($1)>len) $1=substr($1,1,30)"..."; if(length($2)>len) $2=substr($2,1,30)"..."; if(length($3)>len) $3=substr($3,1,30)"..."; printf "%-30s%-35s%-35s%-6s%-38s\n",$1,$2,$3,$4,$5}' FS=\| $file_favorite_tracks | $DMENU_DELETE)
    track_uri=$(echo "$get_track" | awk '{print $NF}')
    track_artist_title=$(awk -F'|' '/'"$track_uri"'/{print $1" - "$2}' $file_favorite_tracks)

    if [[ ! -z $get_track ]]; then
        delete_answer=$(echo -e "Delete '$track_artist_title' from the favorites?\nyes\nno" | $DMENU_DELETE)
        [[ $delete_answer = "yes" ]] && sed -i "/$track_uri/d" $file_favorite_tracks\
        && echo -e "Done:\n'$track_artist_title' deleted from the favorites\n" | $DMENU_DELETE \
        || exit
    else
        exit
    fi

# --- Favorite tracks: LIST ---
elif [[ $input = :fav* ]] || [[ $input = :f ]]; then

    get_track=$(awk -v len=30 'BEGIN{printf "%-30s%-35s%-35s%-6s%-38s%-100s\n","Artist","Title","Album","Time","URI","\n----------------------------------------------------------------------------------------------------------------------------------------------"}{if(length($1)>len) $1=substr($1,1,30)"..."; if(length($2)>len) $2=substr($2,1,30)"..."; if(length($3)>len) $3=substr($3,1,30)"..."; printf "%-30s%-35s%-35s%-6s%-38s\n",$1,$2,$3,$4,$5}' FS=\| $file_favorite_tracks | $DMENU)
    track_uri=$(echo "$get_track" | awk '{print $NF}')

    if [[ ! -z $get_track ]]; then
        $dbus_stop && $dbus_openuri "string:$track_uri"
    else
        exit
    fi

# --- Help ---
elif [[ $input = :help ]] || [[ $input = :h ]]; then
     echo -e "\
         Help\n\
         ======================================================================\n\
         /               Search track (with or without artist)\n\
         /a   /artist    Search artist\n\
         /b   /album     Search album\n\
         ?               Show search history\n\
         :p   :playlist  Switch to the exported playlists\n\
         :a   :add       Add current album to the album list\n\
         :d   :delete    Delete album from the album list\n\
         :f   :fav       Show favorite tracks' list\n\
         :fa  :fadd      Add track to the favorites list\n\
         :fd  :fdel      Delete track from the favorites list\n\
         :i   :info      Show detailed information about the played track/album\n\
         :q   :quit      Quit (close Spotify)\n\
         :h   :help      This help\n\
         ======================================================================\
         " | $DMENU

# --- Load the album list ---
else

    # Transform the custom separator format to the default pipe delimeted format (like in the file_albumlist)
    get_album=$(echo "$input" | awk -v sep="$separator" '{sub(sep,"|");print}')

    # Get the Album ID
    # Use string match (index) instead of regex because the album names can contain special regex characters.
    # Also the list uses pipes as delimeters (and the pipe is a special char in regex).
    album_id=$(awk -F '|' 'index($0, "'"$get_album"'"){print $NF}' $file_albumlist | head -n 1)

    # If no album selected, exit
    if [[ -z $get_album ]]; then
        exit
    else
        # open the album in spotify
        if [[ $autoplay_album = "yes" ]]; then
            track_uri=$(curl --silent -X GET "https://api.spotify.com/v1/albums/$album_id/tracks" | awk -F'"' '/track_number/{i++}i==1 && /uri/ {print $4;exit}')
            $dbus_stop && $dbus_openuri "string:$track_uri"
        # else switch to album and don't autoplay
        else
            $dbus_openuri "string:spotify:album:$album_id"
            # awesome wm - switch to spotify's tag
            if [[ $awm_switch = "yes" ]]; then
                awm_switch_to_tag
            fi
        fi

        # -- DEBUG ---
        #echo -e "input/album: \033[0;33m$input\033[0m"
        #echo -e "get_album: \033[0;33m$get_album\033[0m"
        #echo -e "album_id: \033[0;33m$album_id\033[0m"
        #echo -e "track_uri: \033[0;33m$track_uri\033[0m"
    fi
fi
