#!/bin/bash
#                                      _
#         ___ _ __   ___ _ __ ___   __| |
#        / __| '_ \ / __| '_ ` _ \ / _` |
#        \__ | |_) | (__| | | | | | (_| |
#        |___| .__/ \___|_| |_| |_|\__,_|
#             |_|
#
#                    tunefind
#               Created by: spcmd
#           http://spcmd.github.io
#           https://github.com/spcmd
#           https://gist.github.com/spcmd
#
#

show=$(echo "$1" | sed 's/ /-/g;s/./\L&/g')
season="$2"
episode="$3"
info_color="\033[1;35;4m"
set_color="\033[1;35m"
reset_color="\033[0m"

dump() {
    episode_list=$(curl -s "http://www.tunefind.com/show/$show/season-$season" | awk -F'"' '/.+name="episode[0-9].+"/{print $(NF-1)} /^.+[0-9]\..+[a-zA-Z\(\)\.\?\:]+$/ && !/tunefind/ {gsub("&#039;","\047");gsub(/^[ \t]+/, "");print} ' | awk '{ if ( ( NR % 2 ) == 0 ) { printf("%s\n",$0) } else { printf("%s ",$0"|") } }' | awk -F'|' '{gsub("episode","",$1);print $2"|"$1}')

    ep_id=$(echo "$episode_list" | awk -F'|' '/'"$episode"'\./{print $2;exit}')
    echo "--------------------------------------------------------------------------------"
    echo -e "                   $info_color$show$reset_color season: $info_color$season$reset_color episode: $info_color$episode$reset_color"
    echo "--------------------------------------------------------------------------------"
    lynx -dump -display_charset="UTF-8" -nolist "http://www.tunefind.com/show/shameless/season-$season/$ep_id" | awk -F' by ' '/\*.[a-zA-Z0-9].+by.+$/ {sub(/^[ \t]+/, "");sub(/.+[a-zA-Z0-9]*$/,"'"$set_color"'&'"$reset_color"'",$2);sub(/\* [A-Za-z0-9].+$/,"'"$set_color"'&'"$reset_color"'",$1);sub("*"," -",$1);print "     "$2 $1;flag=1;next} /Get It|No preview available/{flag=0} flag {print}'
}

# Do the stuff
case $1 in
    -h) echo "Usage: $(basename $0) [show title] [season number] [episode number]" ;;
    *) [[ ! -z $1 ]] && [[ ! -z $2 ]] && [[ ! -z $3 ]] && dump | less -ri || echo "Error: You need to specify a show tilte, a season number and an episode number!"
esac
