#!/bin/sh
#                               _
#  ___ _ __   ___ _ __ ___   __| |
# / __| '_ \ / __| '_ ` _ \ / _` |
# \__ | |_) | (__| | | | | | (_| |
# |___| .__/ \___|_| |_| |_|\__,_|
#     |_|
# Created by: spcmd
# http://spcmd.github.io
# https://github.com/spcmd

# Create your own wiki-like notes
# Dependencies: dmenu (or dmenu2), cmark

# Features: - Create new notes in markdown format
#           - Search between them with dmenu
#           - Convert the selected markdown file to html format
#           - Open the html output in your browser

#----------------------------------------------------------------------

# Settings
dir_tuxwiki=$HOME/Documents/tuxwiki
dir_html_output=/tmp
cmd_browser=$BROWSER""
bg_color_code="#AFD2E8"
fg_color_code="#000"
bg_color_codeblock="#f5f5f5"
fg_color_codeblock="#000"

#----------------------------------------------------------------------

# Set dmenu style
[ -f ~/.dmenurc ] && . ~/.dmenurc || DMENU='dmenu -i -l 10'

# create a new file
new() {
    if [ ! -z "$filename" ]; then
        file=$dir_tuxwiki/$filename.md
        echo "# Space separated taglist here..." > "$file"
        $EDITOR "$file"
    else
        echo "Error: no filename was given"
    fi
}

# usage/help
usage() {
cat << EOF

Usage: $(basename "$0") [option] <filename>

Options:
            new, add            create a new file and open in \$EDITOR
            help, -h, --help    this help

EOF
}

# main
main(){

    # List all the files from the dir
    list_files=$(for files in $dir_tuxwiki/*.md; do awk -F'/' 'NR==1{gsub(/\/.*\//,"",FILENAME);gsub("#","",$0);print FILENAME"   [tags: "$0"]"}' "$files"; done)

    # Select a file from dmenu
    get_file=$(echo "$list_files" | $DMENU)

    if [ ! -z "$get_file" ]; then
        # Get the filename
        selected_file=$(echo "$get_file" | awk '{print $1}')

        input_file=$dir_tuxwiki/$selected_file
        output_file=$dir_html_output/$selected_file.html

        # Start creating html file
        echo "<html><head><meta http-equiv='Content-Type' content='text/html;charset=utf-8' /><title>$selected_file</title><style>a {font-size:12px;} code {display:block;font:12px monospace;background:$bg_color_code;color:$fg_color_code;padding:4px} pre code {font:12px monospace;background:$bg_color_codeblock;color:$fg_color_codeblock;padding:8px;border:1px dashed #B0CADA} h1:first-child{text-align:right;font-size:14px;padding:2px;border-bottom:1px solid #666;} h1:first-child:before{content:"tags: ";}ol {padding-left:22px;}</style></head><body>" > "$output_file"

        # Convert the markdown file to html
        cmark "$input_file" -t html >> "$output_file"

        # Finish creating html file
        echo "</body></html>" >> "$output_file"

        # Open in the browser
        $cmd_browser "$output_file"

    else
        exit
    fi
}

# run
case $1 in
    new|add) filename=$2 && new;;
    -h|--help|help) usage;;
    *) main;;
esac
