#!/bin/bash
#                                      _
#         ___ _ __   ___ _ __ ___   __| |
#        / __| '_ \ / __| '_ ` _ \ / _` |
#        \__ | |_) | (__| | | | | | (_| |
#        |___| .__/ \___|_| |_| |_|\__,_|
#             |_|
#
#                 tvd (tv dump) 
#               Created by: spcmd
#           http://spcmd.github.io
#           https://github.com/spcmd
#           https://gist.github.com/spcmd
#

# ===============================
# Configuration
# ===============================
url="http://tvmusor.aweben.hu"
highlight_color="0;33"
use_gap="yes" # yes OR no/empty
# ===============================

# dumping command
dump() {
    lynx -dump -display_charset="UTF-8" -nolist $url/$tv.html | awk -vf=0 '/2016-/{f=1;++d}d!=2{print}f&&d==2{exit};' | sed -e '/^\s*$/d' -ne '/2016-/,$p' | GREP_COLOR="$highlight_color" grep -E --color=always '(^2016-.*|$|[0-9]{2}:[0-9]{2})'
}

# use_gap ?
gap() { 
    if [[ $use_gap = "yes" ]]; then
        echo ""; 
    fi
}

# help 
usage() {
cat <<EOF
Usage: $(basename $0) [channel name]
Optionally you can pipe it to 'less -ri'
    $(basename $0) [channel name] | less -ri

Channel names:

        cool              Cool TV
        tv2               tv2 
        rtl_klub          RTL Klub
        viasat3           Viasat 3
        viasat6           Viasat 6
        super_tv2         Super TV2
        film_p            Film+
        sorozat_p         Sorozat+
        film_cafe         Film Café
        axn               AXN
        amc               AMC
        paramount         Paramaount Channel
        pro4              PRO 4
        rtl_p             RTL+
        story4            Story 4
        story5            Story 5
        rtl_2             RTL II 
        fox               Fox
        m1                m1
        m2                m2
        duna_televizio    Duna TV
        duna_world        Duna World
        comedy_central    Comedy Central
EOF
}

# options (channels)
while : 
do
    case $1 in
        cool) gap && tv=$1 && dump;;
        tv2) gap && tv=$1 && dump;;
        rtl_klub) gap && tv=$1 && dump;;
        viasat3) gap && tv=$1 && dump;;
        viasat6) gap && tv=$1 && dump;;
        super_tv2) gap && tv=$1 && dump;;
        film_p) gap && tv=$1 && dump;;
        sorozat_p) gap && tv=$1 && dump;;
        film_cafe) gap && tv=$1 && dump;;
        axn) gap && tv=$1 && dump;;
        amc) gap && tv=$1 && dump;;
        paramount) gap && tv=$1 && dump;;
        pro4) gap && tv=$1 && dump;;
        rtl_p) gap && tv=$1 && dump;;
        story4) gap && tv=$1 && dump;;
        story5) gap && tv=$1 && dump;;
        rtl_2) gap && tv=$1 && dump;;
        fox) gap && tv=$1 && dump;;
        m1) gap && tv=$1 && dump;;
        m2) gap && tv=$1 && dump;;
        duna_televizio) gap && tv=$1 && dump;;
        duna_world) gap && tv=$1 && dump;;
        comedy_central) gap && tv=$1 && dump;;
        -h|--help|help) usage;;
        *) break;;
    esac
    shift
done
